export const FORMULAS = {
  subcarrierSpacing: String.raw`\Delta f = \frac{1}{T_u}`,
  rangeResolution: String.raw`\Delta R = \frac{c}{2B}`,
  velocityResolution: String.raw`\Delta v = \frac{c}{2f_cMT_{\mathrm{sym}}}`,
  delayAndDoppler: String.raw`\tau = \frac{2R}{c}\qquad f_D = \frac{2vf_c}{c}`,
  echoResponse: String.raw`H[k,m] = \beta\,\exp(-j2\pi k\Delta f\tau)\,\exp(j2\pi f_DmT_{\mathrm{sym}})`,
  speedOfLight: String.raw`c = 299\,792\,458\;\mathrm{m/s}`,
  bandwidthSpacing: String.raw`\Delta f = \frac{B}{N}`,
  symbolDuration: String.raw`T_{\mathrm{sym}} = \frac{1{,}25}{\Delta f}`,
  qpskRate: String.raw`R_{\mathrm{QPSK}} = \frac{2N}{T_{\mathrm{sym}}}\;\mathrm{bit/s}`,
  wavelength: String.raw`\lambda = \frac{c}{f_c}\;[\mathrm{m}]`,
  doppler: String.raw`f_D = \frac{2vf_c}{c}\;[\mathrm{Hz}]`,
  ber: String.raw`\mathrm{BER} = \frac{\text{bits erróneos}}{\text{bits transmitidos}}`,
  snr: String.raw`\mathrm{SNR}_{\mathrm{dB}} = 10\log_{10}\!\left(\frac{P_{\text{señal}}}{P_{\text{ruido}}}\right)\;[\mathrm{dB}]`,
  detectionProbability: String.raw`P_d = P(\text{declarar objetivo}\mid\text{objetivo presente})`,
  crlb: String.raw`\operatorname{Var}(\hat{R}) \ge \operatorname{CRLB}_{R}\;[\mathrm{m}^2]`,
  powerSplit: String.raw`P_c = \alpha P_{\mathrm{total}}, \qquad P_s = (1-\alpha)\,P_{\mathrm{total}}, \qquad 0 \le \alpha \le 1`,
  shannonCapacity: String.raw`R = B\,\log_2\!\left(1 + \mathrm{SNR}_{\mathrm{com}}\right) \;[\mathrm{bit/s}]`,
  commSnr: String.raw`\mathrm{SNR}_{\mathrm{com}} = \frac{|h|^2\,P_c}{k\,T_0\,B\,F}`,
  radarSnr: String.raw`\mathrm{SNR}_{\mathrm{radar}} = \frac{P_s\,G^2\lambda^2\,\sigma}{(4\pi)^3\,R^4\,k\,T_0\,B\,F}`,
} as const;
